version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: none
  web:
    container_name: news_api
    build: .
    command: bash -c "alembic upgrade head && python ./main.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: