"""migration

Revision ID: d065859698b1
Revises: c298a8697cd3
Create Date: 2023-09-18 00:19:46.219238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd065859698b1'
down_revision: Union[str, None] = 'c298a8697cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metro_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date_published', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline')
    )
    op.create_index(op.f('ix_metro_news_id'), 'metro_news', ['id'], unique=False)
    op.drop_index('ix_metro_news_new_id', table_name='metro_news_new')
    op.drop_table('metro_news_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metro_news_new',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_published', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metro_news_new_pkey'),
    sa.UniqueConstraint('headline', name='metro_news_new_headline_key')
    )
    op.create_index('ix_metro_news_new_id', 'metro_news_new', ['id'], unique=False)
    op.drop_index(op.f('ix_metro_news_id'), table_name='metro_news')
    op.drop_table('metro_news')
    # ### end Alembic commands ###
